### ISSUE TITLE
Isaiah docker container won't stop

### ISSUE THREAD

**Issue by tryolly** [will-moss/isaiah#20]
When I try to stop the isaiah container with `sudo docker compose -f isaiah.yaml down` nothing happens, the container continues to run. The same thing happens with `docker stop <container_id>` as well.

Any idea how to fix this? My compose file is as follows:

```
name: isaiah
services:
  isaiah:
    image: mosswill/isaiah:latest
    container_name: isaiah
    environment:
      SERVER_PORT: "8000"
      AUTHENTICATION_HASH: "*******"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - isaiah # dynamic IP
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

networks:
  isaiah:
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/24"

```
