### ISSUE TITLE
Is it possible to work with an existing stack?

### ISSUE THREAD

**Issue by reorx** [will-moss/isaiah#8]
I have a Docker stack at `/root/mystack/docker-compose.yml`. I tried the following configuration, but the stack doesn't appear on Isaiah's interface. Did I make a mistake, or is this configuration not supported? 

```
version: '3'
services:
  isaiah:
    image: myregistry/isaiah
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/mystack:/stacks
    environment:
      STACKS_DIRECTORY: "/stacks"
```
